name: Label Pull Requests Based on File Changes

on:
  pull_request:
    paths:
      - 'assets/**'
      - '.gitattributes'

permissions:
  contents: read
  pull-requests: write
  issues: write
env:
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - name: Label PR
        uses: actions/labeler@v4
        with:
          repo-token: '${{ secrets.Workflow_PAT }}'
          configuration-path: .github/labeler.yml
